const irregularVerbs = [
  { "id": 1, "base": "be", "past": "was, were", "pastParticiple": "been", "bangla": "হওয়া" }, // [cite: 3]
  { "id": 2, "base": "become", "past": "became", "pastParticiple": "become", "bangla": "হওয়া/পরিণত হওয়া" }, // [cite: 3]
  { "id": 3, "base": "begin", "past": "began", "pastParticiple": "begun", "bangla": "শুরু করা" }, // [cite: 3]
  { "id": 4, "base": "bet", "past": "bet", "pastParticiple": "bet", "bangla": "বাজি ধরা" }, // [cite: 3]
  { "id": 5, "base": "bite", "past": "bit", "pastParticiple": "bitten", "bangla": "কামড়ানো" }, // [cite: 3]
  { "id": 6, "base": "bleed", "past": "bled", "pastParticiple": "bled", "bangla": "রক্তক্ষরণ হওয়া" }, // [cite: 3]
  { "id": 7, "base": "blow", "past": "blew", "pastParticiple": "blown", "bangla": "ফুঁ দেওয়া/প্রবাহিত হওয়া" }, // [cite: 3]
  { "id": 8, "base": "break", "past": "broke", "pastParticiple": "broken", "bangla": "ভাঙা" }, // [cite: 3]
  { "id": 9, "base": "bring", "past": "brought", "pastParticiple": "brought", "bangla": "আনা" }, // [cite: 3]
  { "id": 10, "base": "build", "past": "built", "pastParticiple": "built", "bangla": "নির্মাণ করা" }, // [cite: 3]
  { "id": 11, "base": "burn", "past": "burnt, burned", "pastParticiple": "burnt, burned", "bangla": "পোড়ানো" }, // [cite: 3]
  { "id": 12, "base": "buy", "past": "bought", "pastParticiple": "bought", "bangla": "কেনা" }, // [cite: 3]
  { "id": 13, "base": "can", "past": "could", "pastParticiple": "been able to", "bangla": "পারা" }, // [cite: 3]
  { "id": 14, "base": "catch", "past": "caught", "pastParticiple": "caught", "bangla": "ধরা" }, // [cite: 3]
  { "id": 15, "base": "choose", "past": "chose", "pastParticiple": "chosen", "bangla": "পছন্দ করা" }, // [cite: 3]
  { "id": 16, "base": "come", "past": "came", "pastParticiple": "come", "bangla": "আসা" }, // [cite: 3]
  { "id": 17, "base": "cost", "past": "cost", "pastParticiple": "cost", "bangla": "মূল্য হওয়া" }, // [cite: 3]
  { "id": 18, "base": "cut", "past": "cut", "pastParticiple": "cut", "bangla": "কাটা" }, // [cite: 3]
  { "id": 19, "base": "deal", "past": "dealt", "pastParticiple": "dealt", "bangla": "লেনদেন করা" }, // [cite: 3]
  { "id": 20, "base": "do", "past": "did", "pastParticiple": "done", "bangla": "করা" }, // [cite: 3]
  { "id": 21, "base": "draw", "past": "drew", "pastParticiple": "drawn", "bangla": "আঁকা" }, // [cite: 3]
  { "id": 22, "base": "dream", "past": "dreamt, dreamed", "pastParticiple": "dreamt, dreamed", "bangla": "স্বপ্ন দেখা" }, // [cite: 3]
  { "id": 23, "base": "drink", "past": "drank", "pastParticiple": "drunk", "bangla": "পান করা" }, // [cite: 3]
  { "id": 24, "base": "drive", "past": "drove", "pastParticiple": "driven", "bangla": "চালানো" }, // [cite: 3]
  { "id": 25, "base": "eat", "past": "ate", "pastParticiple": "eaten", "bangla": "খাওয়া" }, // [cite: 3]
  { "id": 26, "base": "fall", "past": "fell", "pastParticiple": "fallen", "bangla": "পড়া" }, // [cite: 3]
  { "id": 27, "base": "feel", "past": "felt", "pastParticiple": "felt", "bangla": "অনুভব করা" }, // [cite: 3]
  { "id": 28, "base": "fight", "past": "fought", "pastParticiple": "fought", "bangla": "যুদ্ধ করা" }, // [cite: 3]
  { "id": 29, "base": "find", "past": "found", "pastParticiple": "found", "bangla": "খুঁজে পাওয়া" }, // [cite: 3]
  { "id": 30, "base": "fly", "past": "flew", "pastParticiple": "flown", "bangla": "ওড়া" }, // [cite: 3]
  { "id": 31, "base": "forget", "past": "forgot", "pastParticiple": "forgotten", "bangla": "ভুলে যাওয়া" }, // [cite: 3]
  { "id": 32, "base": "forgive", "past": "forgave", "pastParticiple": "forgiven", "bangla": "ক্ষমা করা" }, // [cite: 3]
  { "id": 33, "base": "freeze", "past": "froze", "pastParticiple": "frozen", "bangla": "জমে যাওয়া" }, // [cite: 3]
  { "id": 34, "base": "get", "past": "got", "pastParticiple": "got (AmE gotten)", "bangla": "পাওয়া" }, // [cite: 3]
  { "id": 35, "base": "give", "past": "gave", "pastParticiple": "given", "bangla": "দেওয়া" }, // [cite: 3]
  { "id": 36, "base": "go", "past": "went", "pastParticiple": "gone, been", "bangla": "যাওয়া" }, // [cite: 3]
  { "id": 37, "base": "grow", "past": "grew", "pastParticiple": "grown", "bangla": "বৃদ্ধি পাওয়া" }, // [cite: 3]
  { "id": 38, "base": "hang", "past": "hung", "pastParticiple": "hung", "bangla": "ঝুলানো" }, // [cite: 3]
  { "id": 39, "base": "have", "past": "had", "pastParticiple": "had", "bangla": "আছে/থাকা" }, // [cite: 3]
  { "id": 40, "base": "hear", "past": "heard", "pastParticiple": "heard", "bangla": "শোনা" }, // [cite: 3]
  { "id": 41, "base": "hide", "past": "hid", "pastParticiple": "hidden", "bangla": "লুকানো" }, // [cite: 3]
  { "id": 42, "base": "hit", "past": "hit", "pastParticiple": "hit", "bangla": "আঘাত করা" }, // [cite: 3]
  { "id": 43, "base": "hold", "past": "held", "pastParticiple": "held", "bangla": "ধরা/ধরে রাখা" }, // [cite: 3]
  { "id": 44, "base": "hurt", "past": "hurt", "pastParticiple": "hurt", "bangla": "আঘাত করা" }, // [cite: 3]
  { "id": 45, "base": "keep", "past": "kept", "pastParticiple": "kept", "bangla": "রাখা" }, // [cite: 3]
  { "id": 46, "base": "know", "past": "knew", "pastParticiple": "known", "bangla": "জানা" }, // [cite: 3]
  { "id": 47, "base": "lay", "past": "laid", "pastParticiple": "laid", "bangla": "শায়িত করা/ডিম পাড়া" }, // [cite: 3]
  { "id": 48, "base": "lead", "past": "led", "pastParticiple": "led", "bangla": "নেতৃত্ব দেওয়া" }, // [cite: 3]
  { "id": 49, "base": "learn", "past": "learnt, learned", "pastParticiple": "learnt, learned", "bangla": "শেখা" }, // [cite: 3]
  { "id": 50, "base": "leave", "past": "left", "pastParticiple": "left", "bangla": "ছেড়ে যাওয়া" }, // [cite: 3]
  { "id": 51, "base": "lend", "past": "lent", "pastParticiple": "lent", "bangla": "ধার দেওয়া" }, // [cite: 6]
  { "id": 52, "base": "let", "past": "let", "pastParticiple": "let", "bangla": "অনুমতি দেওয়া" }, // [cite: 6]
  { "id": 53, "base": "light", "past": "lit", "pastParticiple": "lit", "bangla": "আলো জ্বালানো" }, // [cite: 6]
  { "id": 54, "base": "lose", "past": "lost", "pastParticiple": "lost", "bangla": "হারানো" }, // [cite: 6]
  { "id": 55, "base": "make", "past": "made", "pastParticiple": "made", "bangla": "তৈরি করা" }, // [cite: 6]
  { "id": 56, "base": "mean", "past": "meant", "pastParticiple": "meant", "bangla": "অর্থ প্রকাশ করা" }, // [cite: 6]
  { "id": 57, "base": "meet", "past": "met", "pastParticiple": "met", "bangla": "সাক্ষাৎ করা" }, // [cite: 6]
  { "id": 58, "base": "pay", "past": "paid", "pastParticiple": "paid", "bangla": "পরিশোধ করা" }, // [cite: 6]
  { "id": 59, "base": "put", "past": "put", "pastParticiple": "put", "bangla": "রাখা" }, // [cite: 6]
  { "id": 60, "base": "read", "past": "read", "pastParticiple": "read", "bangla": "পড়া" }, // [cite: 6]
  { "id": 61, "base": "ride", "past": "rode", "pastParticiple": "ridden", "bangla": "চড়া (সাইকেল/ঘোড়া)" }, // [cite: 6]
  { "id": 62, "base": "ring", "past": "rang", "pastParticiple": "rung", "bangla": "ঘণ্টা বাজানো" }, // [cite: 6]
  { "id": 63, "base": "rise", "past": "rose", "pastParticiple": "risen", "bangla": "উঠা" }, // [cite: 6]
  { "id": 64, "base": "run", "past": "ran", "pastParticiple": "run", "bangla": "দৌড়ানো" }, // [cite: 6]
  { "id": 65, "base": "say", "past": "said", "pastParticiple": "said", "bangla": "বলা" }, // [cite: 6]
  { "id": 66, "base": "see", "past": "saw", "pastParticiple": "seen", "bangla": "দেখা" }, // [cite: 6]
  { "id": 67, "base": "sell", "past": "sold", "pastParticiple": "sold", "bangla": "বিক্রি করা" }, // [cite: 6]
  { "id": 68, "base": "send", "past": "sent", "pastParticiple": "sent", "bangla": "পাঠানো" }, // [cite: 6]
  { "id": 69, "base": "set", "past": "set", "pastParticiple": "set", "bangla": "স্থাপন করা" }, // [cite: 6]
  { "id": 70, "base": "shake", "past": "shook", "pastParticiple": "shaken", "bangla": "ঝাঁকানো" }, // [cite: 6]
  { "id": 71, "base": "shine", "past": "shone", "pastParticiple": "shone", "bangla": "কিরণ দেওয়া" }, // [cite: 6]
  { "id": 72, "base": "shoot", "past": "shot", "pastParticiple": "shot", "bangla": "গুলি করা" }, // [cite: 6]
  { "id": 73, "base": "show", "past": "showed", "pastParticiple": "shown", "bangla": "দেখানো" }, // [cite: 6]
  { "id": 74, "base": "shut", "past": "shut", "pastParticiple": "shut", "bangla": "বন্ধ করা" }, // [cite: 6]
  { "id": 75, "base": "sing", "past": "sang", "pastParticiple": "sung", "bangla": "গান গাওয়া" }, // [cite: 6]
  { "id": 76, "base": "sink", "past": "sank", "pastParticiple": "sunk", "bangla": "ডুবে যাওয়া" }, // [cite: 6]
  { "id": 77, "base": "sit", "past": "sat", "pastParticiple": "sat", "bangla": "বসা" }, // [cite: 6]
  { "id": 78, "base": "sleep", "past": "slept", "pastParticiple": "slept", "bangla": "ঘুমানো" }, // [cite: 6]
  { "id": 79, "base": "smell", "past": "smelt, smelled", "pastParticiple": "smelt, smelled", "bangla": "ঘ্রাণ নেওয়া" }, // [cite: 6]
  { "id": 80, "base": "speak", "past": "spoke", "pastParticiple": "spoken", "bangla": "কথা বলা" }, // [cite: 6]
  { "id": 81, "base": "spell", "past": "spelt, spelled", "pastParticiple": "spelt, spelled", "bangla": "বানান করা" }, // [cite: 6]
  { "id": 82, "base": "spend", "past": "spent", "pastParticiple": "spent", "bangla": "ব্যয় করা" }, // [cite: 6]
  { "id": 83, "base": "spill", "past": "spilt, spilled", "pastParticiple": "spilt, spilled", "bangla": "ছড়িয়ে পড়া/ফেলা" }, // [cite: 6]
  { "id": 84, "base": "split", "past": "split", "pastParticiple": "split", "bangla": "বিভক্ত করা" }, // [cite: 6]
  { "id": 85, "base": "spoil", "past": "spoilt, spoiled", "pastParticiple": "spoilt, spoiled", "bangla": "নষ্ট করা" }, // [cite: 6]
  { "id": 86, "base": "spread", "past": "spread", "pastParticiple": "spread", "bangla": "ছড়িয়ে দেওয়া" }, // [cite: 6]
  { "id": 87, "base": "stand", "past": "stood", "pastParticiple": "stood", "bangla": "দাঁড়ানো" }, // [cite: 6]
  { "id": 88, "base": "steal", "past": "stole", "pastParticiple": "stolen", "bangla": "চুরি করা" }, // [cite: 6]
  { "id": 89, "base": "stick", "past": "stuck", "pastParticiple": "stuck", "bangla": "আটকে থাকা" }, // [cite: 6]
  { "id": 90, "base": "swim", "past": "swam", "pastParticiple": "swum", "bangla": "সাঁতার কাটা" }, // [cite: 6]
  { "id": 91, "base": "take", "past": "took", "pastParticiple": "taken", "bangla": "নেওয়া" }, // [cite: 6]
  { "id": 92, "base": "teach", "past": "taught", "pastParticiple": "taught", "bangla": "শিক্ষা দেওয়া" }, // [cite: 6]
  { "id": 93, "base": "tell", "past": "told", "pastParticiple": "told", "bangla": "বলা" }, // [cite: 6]
  { "id": 94, "base": "think", "past": "thought", "pastParticiple": "thought", "bangla": "চিন্তা করা" }, // [cite: 6]
  { "id": 95, "base": "throw", "past": "threw", "pastParticiple": "thrown", "bangla": "নিক্ষেপ করা" }, // [cite: 6]
  { "id": 96, "base": "understand", "past": "understood", "pastParticiple": "understood", "bangla": "বুঝতে পারা" }, // [cite: 6]
  { "id": 97, "base": "upset", "past": "upset", "pastParticiple": "upset", "bangla": "বিচলিত করা" }, // [cite: 6]
  { "id": 98, "base": "wake", "past": "woke", "pastParticiple": "woken", "bangla": "জেগে উঠা" }, // [cite: 6]
  { "id": 99, "base": "wear", "past": "wore", "pastParticiple": "worn", "bangla": "পরিধান করা" }, // [cite: 6]
  { "id": 100, "base": "win", "past": "won", "pastParticiple": "won", "bangla": "জয়লাভ করা" }, // [cite: 6]
  { "id": 101, "base": "write", "past": "wrote", "pastParticiple": "written", "bangla": "লেখা" } // [cite: 6]
];